apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  type: LoadBalancer
  selector:
    app: test  
  ports:
    - protocol: TCP 
      port: 5000
      targetPort: 3000
      nodePort: 31111
